#! /usr/bin/env python
# -*- coding: utf-8 -*-

import cv2

t=0
img = cv2.imread('HojasP2.png',cv2.IMREAD_COLOR)
h,w,p = img.shape     #devuelve el tamaño de la imagen ancho y alto
print('alto = ',h)
print('ancho =',w)

# Agregar código aquí
print('valor de t es ',t)
print('Desea cambiar a escala de grises?')
cv2.imshow('PRACTICO 2 IMG', img)	#muestra imagen

t=cv2.waitKey(5000) & 0xFF 

print('nuevo valor de t es ',t)
c=200	
# Para resolverlo podemos usar dos for anidados
	
if t == ord('s'):

	for i in range (h):				
	    for j in range (w): 
		print('valores',img[50,50])
		

#	        if(img[i,j] > c):
#	            img[i,j] = 0,0,0
	print('La imagen cambió')
	cv2. imwrite ('resultado.png' , img)
	
else:
    print('La imagen no cambió')
    
cv2.imshow('IMAGEN ORIGINAL', img)
print('ultimo valor de t es ',t)
print('este es el final')
cv2.waitKey(5000)
